### ISSUE TITLE
Usage of a dev version

### ISSUE THREAD

**Issue by lersi** [Sentinel-One/brick#8]
Why are you using develop branch of project bip?

may be you should specify it in the read me?

**Comment by assafcarlsbad** [comment]
Hi,
Sorry for the lack of responsiveness on my side.
As for your question - the develop branch of Bip offers some extra utilities and functions that are (still) not part of the master branch, some of it actually used by brick.
The `install.py` script already downloads and installs the develop version, but I'll make sure to add that to the README file as well.
Thanks!

(I'm closing the issue for now, feel free to re-open it if you have further questions)
